services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paytm-seat-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      ADMIN_TOKEN: ${ADMIN_TOKEN}

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: seat_reservation
      DB_USERNAME: seat_user
      DB_PASSWORD: seat_password
      PHP_CLI_SERVER_WORKERS: "8"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: paytm-seat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: seat_reservation
      POSTGRES_USER: seat_user
      POSTGRES_PASSWORD: seat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seat_user -d seat_reservation"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: